#!/bin/bash
FROM ubuntu:latest
#Variables a suministrar en el momento de crear la imagen del contenedor
ARG FICHERO_CONFIGURACION_NGINX=configuracion.nginx # Valor por defecto

RUN apt update
RUN apt install nginx -y
RUN apt install git -y
RUN git clone https://github.com/IvanciniGT/webEjemploAnsible /www
#RUN cp -rv /tmp/web/* /www

COPY $FICHERO_CONFIGURACION_NGINX /etc/nginx/sites-available/default

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
