version: "3"

services:
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db # Hasta que el servicio db no esté arrancado, no se arrancará el contenedor de sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /home/ubuntu/environment/datos/sonarqube/data:/opt/sonarqube/data
      - /home/ubuntu/environment/datos/sonarqube/extensions:/opt/sonarqube/extensions
      - /home/ubuntu/environment/datos/sonarqube/logs:/opt/sonarqube/logs
    ports:
      - "8081:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /home/ubuntu/environment/datos/sonarqube/postgresql/postgresql:/var/lib/postgresql
      - /home/ubuntu/environment/datos/sonarqube/postgresql/data:/var/lib/postgresql/data
